# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Samuel Q
email: hgkim999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.samuelkim.me" # the base hostname & protocol for your site
github_username:  hgkim999
repository: https://github.com/hgkim999/page.git
# Build settings
markdown: kramdown
source: .
destination: ./_site

theme: jekyll-theme-minimal
sass:
    style: compressed
    sass_dir: _sass
